name: Update NFL Play-by-Play Data

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  schedule:
    - cron: '0 8 * * TUE' # Runs at 8:00 AM UTC every Tuesday

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: true # Make sure to checkout LFS files

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nfl_data_py pandas pyarrow

      - name: Run data update script
        run: python update_data.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          # Check if there are changes to commit
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Automated data update"
            git push
          else
            echo "No data changes to commit."
          fi